apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldv2
  labels:
    app: helloworldv2
  
  annotations:
    monitoring: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworldv2
  template:
    metadata:
      labels:
        app: helloworldv2
    spec:
      containers:
      - image: kriti2k5/helloworld:1.0.0
        name: helloworldv2
        ports:
        - containerPort: 3000
