apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworldv2
  name: helloworldv2
 
spec:
  ports:
  - nodePort: 30505
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: helloworldv2
  type: NodePort
