apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworldv2
  name: helloworldv2
 
spec:
  ports:
  - nodePort: 40500
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helloworldv2
  type: NodePort
